require: sudo
language: node_js
node_js:
  - "6.5"
branches:
  only:
  - develop
  - master
  - /^release-.*$/
  - /^hotfix-.*$/
  - /^v\d+\.\d+\.\d+$/
webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e3f30c04846ed5b54c0
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
install:
 - node --version
 - cd ../
 - pwd
 - git clone --depth=1 --no-single-branch https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
 - cd $TRAVIS_REPO_SLUG
 - pwd
 - echo $TRAVIS_BRANCH
 - echo $TRAVIS_TAG
 - git branch -a
 - git checkout $TRAVIS_BRANCH
 - npm i
script: 
 - npm run test:coverage
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh .demo-publish.sh
  on:
    tags: true
    condition: $TRAVIS_TAG != ""

