require: sudo
language: node_js
node_js:
  - "6.5"
branches:
  only:
  - develop
  - master
  - /^release-.*$/
  - /^hotfix-.*$/
webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e3f30c04846ed5b54c0
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - npm i -g yarn --cache-min 999999999

install:
 - node --version
 - yarn install
script: 
 - yarn test:coverage

cache: yarn

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: /bin/sh .deploy.sh
#   on:
#     branch: master