require: sudo
language: node_js
node_js:
  - "6.5"
script: 
  /bin/sh .travis.sh
branches:
  only:
  - develop
  - master
  - /^release-.*$/
  - /^hotfix-.*$/
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: /bin/sh .deploy.sh
#   on:
#     branch: master